# Generated by Django 6.1 on 2026-08-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_date',
            field=models.DateTimeField(),
        ),
    ]
