# Generated by Django 6.1 on 2026-08-20 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_Management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='bookdetails',
        ),
        migrations.AddField(
            model_name='bookdetails',
            name='book',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='Library_Management.books'),
        ),
    ]
